Removes the restriction on mimes and clowns
Towelstation13/towelstation13 pull request #7
Opened 2023-09-10 18:06 UTC by xPokee

## About The Pull Request
I don't know why it was like that, but people complained

## How This Contributes To The Skyrat Roleplay Experience
honk

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
config: Mine and clown are no longer locked behind veteran
/:cl:

2023-09-10 18:09 UTC, distributivgesetz approved these changes

2023-09-10 18:10 UTC, distributivgesetz commented
could also remove the `veteran_only` variable

2023-09-10 18:13 UTC, xPokee commented
> could also remove the `veteran_only` variable

Want me to do that instead?

2023-09-10 19:17 UTC, distributivgesetz commented
yeah

2023-09-10 20:33 UTC, distributivgesetz requested changes
Can you either remove this file or remove the field altogether? We want to decommission the veteran system, so we don't need to keep it around.

2023-09-11 13:49 UTC, distributivgesetz requested changes

2023-09-11 13:49 UTC, distributivgesetz commented on tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx
> +              {species.map(([speciesKey, species]) => {})}
This nukes the entirety of the species selection list. Please only remove the veteran early return as well as the tooltip wrapper.

2023-09-11 13:49 UTC, distributivgesetz commented on code/modules/mob/dead/new_player/new_player.dm
> -		return JOB_NOT_VETERAN
Remove this define

2023-09-11 13:49 UTC, distributivgesetz commented on modular_skyrat/modules/player_ranks/code/player_rank_controller/veteran_controller.dm
> -	return CONFIG_GET(flag/veteran_legacy_system)
Remove these config options from `modular_skyrat\master_files\code\controllers\configuration\entries\skyrat_config_entries.dm`.

2023-09-11 17:41 UTC, distributivgesetz reviewed
Lgtm, one last thing, remove `#define JOB_NOT_VETERAN` then I'd say this is ready to merge.

2023-09-11 17:43 UTC, distributivgesetz commented on tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx
> -import { classes } from 'common/react';
Reimport this.

2023-09-11 17:45 UTC, distributivgesetz approved these changes

2023-09-11 18:18 UTC, merged